# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - task: Npm@1
    displayName: 'Install Azure Function Core Tools'
    inputs:
      command: 'custom'
      customCommand: 'i -g azure-functions-core-tools@3 --unsafe-perm true'

  - task: Npm@1
    displayName: 'Install Application Dependencies'
    inputs:
      command: install
      workingDir: '$(System.DefaultWorkingDirectory)'
      verbose: false

  - task: WhiteSource Bolt@20
    displayName: 'WhiteSOurce Bolt'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '$(System.DefaultWorkingDirectory)'
      customCommand: 'run build --if-present'
    displayName: 'Run build script'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run test:ci'
    displayName: 'Run Unit Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results junit.xml'
    inputs:
      testResultsFiles: junit.xml
      searchFolder: '$(System.DefaultWorkingDirectory)/testing'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from  $(System.DefaultWorkingDirectory)/testing/coverage/cobertura-coverage.xml'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: ' $(System.DefaultWorkingDirectory)/testing/coverage/cobertura-coverage.xml'

  - task: Npm@1
    displayName: 'Remove extraneous packages'
    inputs:
      command: custom
      workingDir: '$(System.DefaultWorkingDirectory)'
      verbose: false
      customCommand: 'prune --production'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
